### ISSUE TITLE
ocw-www: make image required on promo

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-hugo-projects#147]
Currently, the build will fail if a promo doesn't have an image. 

to maintain the page layout it seems like the easiest thing to do is require an image for all promos.

**Comment by MAbdurrehman12** [comment]
It looks like that `required: true` is not working for `widget: relation`. I tried to do some RnD on this issue and it turns out to be an issue in ocw-studio in this [function](https://github.com/mitodl/ocw-studio/blob/7d86d5701236bb775a3f02c7dfce42a1381bb9c7/static/js/components/forms/validation.ts#L58), as in case of `widget=relation`, `yup.object` is being created with a content field [here](https://github.com/mitodl/ocw-studio/blob/7d86d5701236bb775a3f02c7dfce42a1381bb9c7/static/js/components/forms/validation.ts#L67) and `required()` is being called on that ([here](https://github.com/mitodl/ocw-studio/blob/7d86d5701236bb775a3f02c7dfce42a1381bb9c7/static/js/components/forms/validation.ts#L121)) instead of the `content field` inside. 
This might also be the case with `widget:Object` but I haven't tested it.  

Though I'm not very sure as I haven't worked much with React formik. @alicewriteswrongs Do you have any thoughts on this?
